// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collector} from '../models';
import {config} from '../models';
import {forecast} from '../models';
import {time} from '../models';
import {store} from '../models';

export function EmitSample(arg1:collector.Snapshot):Promise<void>;

export function EmitStatus(arg1:string):Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function Start():Promise<void>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;

export function ViewForecast():Promise<forecast.Result>;

export function ViewHourly(arg1:time.Time,arg2:time.Time,arg3:string,arg4:string):Promise<Array<store.HourlyRollup>>;

export function ViewTotals(arg1:time.Time,arg2:time.Time,arg3:string):Promise<Array<store.KeyTotal>>;
