// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitSample(arg1) {
  return window['go']['app']['App']['EmitSample'](arg1);
}

export function EmitStatus(arg1) {
  return window['go']['app']['App']['EmitStatus'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function Start() {
  return window['go']['app']['App']['Start']();
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function ViewForecast() {
  return window['go']['app']['App']['ViewForecast']();
}

export function ViewHourly(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ViewHourly'](arg1, arg2, arg3, arg4);
}

export function ViewTotals(arg1, arg2, arg3) {
  return window['go']['app']['App']['ViewTotals'](arg1, arg2, arg3);
}
