// @ts-check
// This file is automatically generated by Wails. DO NOT EDIT.
// (Manually written as a placeholder matching the App struct in
//  internal/app/app.go. Wails will overwrite it on the next `wails dev`.)

export function Startup(arg1) {
    return window['go']['app']['App']['Startup'](arg1);
}

export function Shutdown(arg1) {
    return window['go']['app']['App']['Shutdown'](arg1);
}

export function Start() {
    return window['go']['app']['App']['Start']();
}

export function GetSettings() {
    return window['go']['app']['App']['GetSettings']();
}

export function UpdateSettings(arg1) {
    return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function ViewTotals(arg1, arg2, arg3) {
    return window['go']['app']['App']['ViewTotals'](arg1, arg2, arg3);
}

export function ViewHourly(arg1, arg2, arg3, arg4) {
    return window['go']['app']['App']['ViewHourly'](arg1, arg2, arg3, arg4);
}

export function ViewForecast() {
    return window['go']['app']['App']['ViewForecast']();
}
